import js from '@eslint/js';
import babelParser from '@babel/eslint-parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import importPlugin from 'eslint-plugin-import';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    files: ['**/*.js', '**/*.jsx'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      import: importPlugin,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {
          presets: ['@babel/preset-react', '@babel/preset-env'],
        },
        ecmaVersion: 2020,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        Notification: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
        process: 'readonly',
        module: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    rules: {
      eqeqeq: 2,
      'comma-dangle': 0,
      'no-console': 0,
      'no-debugger': 1,
      'no-extra-semi': 1,
      'no-extra-parens': 0,
      'no-irregular-whitespace': 0,
      'no-undef': 0,
      'no-unused-vars': 0,
      'no-prototype-builtins': 0,
      semi: 1,
      'semi-spacing': 1,
      'valid-jsdoc': [2, { requireReturn: false }],
      'import/extensions': 1,
      indent: ['error', 4, { SwitchCase: 1 }],
      'max-len': ['error', { code: 160 }],
      'react/display-name': 2,
      'react/forbid-prop-types': 1,
      'react/jsx-boolean-value': 1,
      'react/jsx-closing-bracket-location': 1,
      'react/jsx-curly-spacing': 1,
      'react/jsx-indent-props': [2, 4],
      'react/jsx-max-props-per-line': 0,
      'react/jsx-no-duplicate-props': 1,
      'react/jsx-no-literals': 0,
      'react/jsx-no-undef': 1,
      'react/sort-prop-types': 0,
      'react/jsx-sort-props': 0,
      'react/jsx-uses-react': 1,
      'react/jsx-uses-vars': 1,
      'react/no-danger': 1,
      'react/no-did-mount-set-state': 0,
      'react/no-did-update-set-state': 1,
      'react/no-direct-mutation-state': 1,
      'react/no-multi-comp': [1, { ignoreStateless: true }],
      'react/no-set-state': 0,
      'react/no-unknown-property': 1,
      'react/no-unescaped-entities': 0,
      'react/prop-types': 0,
      'react/react-in-jsx-scope': 0,
      'react/self-closing-comp': 1,
      'react/sort-comp': 1,
      'react/jsx-wrap-multilines': 1,
      'no-param-reassign': 0,
      'no-use-before-define': 'off',
      'no-empty-label': 0,
      'space-after-keywords': 0,
      'space-return-throw-case': 0,
    },
  },
  prettier,
];
